version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - storybook
      sanity:
        patterns:
          - "@sanity/*"
          - groq
          - sanity
      puppeteer:
        patterns:
          - "@types/jest-environment-puppeteer"
          - "@types/puppeteer"
          - puppeteer-core
          - puppeteer

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
