name: Code style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate-code:
    name: Validate code style
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run format:check
