name: Code style

on:
  pull_request:

jobs:
  validate-code:
    name: Validate code style

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install npm packages
        uses: bahmutov/npm-install@v1

      - run: npm run format:check
